"""Proto-tools allowlist and cost model.

This exists for one reason: a model asked to design a computational fitness
cascade will happily invent a tool that does exactly what the design needs.
`validate.py` rejects any gate naming a key that is not here, so a hallucinated
capability fails the run instead of reaching the Modal agent as an instruction.

IMPORTANT — this list is a *hallucination guard*, not ground truth. It was
transcribed from the proto-tools catalogue and will drift. The downstream Proto
agent must confirm every key with `search_tools` / `list_tools` before running
anything, per `.claude/skills/proto-tools/SKILL.md`. A key being present here
does not mean it is deployed on the user's Modal workspace, and deployment is
billable.
"""

from __future__ import annotations

import json
from pathlib import Path

# --------------------------------------------------------------------------
# tool keys and metrics, from the generated registry snapshot
# --------------------------------------------------------------------------
# Generated by `litkb proto-sync --snapshot`. Committed so this project stays
# offline and has no runtime dependency on the `proto` venv.
#
# This replaces a hand-transcribed list that had drifted badly: measured
# against the live catalogue, 1 of its 59 tool keys was real (the rest were
# bare model names, where proto-tools keys are `<model>-<action>`), and 20 of
# its 27 metrics were emitted by no tool at all. A hallucination guard that
# rejects the real names and accepts invented ones is worse than none.
_SNAPSHOT_PATH = Path(__file__).resolve().parents[3] / "registry" / "proto_metrics.json"

with _SNAPSHOT_PATH.open() as _fh:
    _SNAPSHOT = json.load(_fh)

PROTO_TOOL_KEYS: frozenset[str] = frozenset(_SNAPSHOT["tool_keys"])
PROTO_METRICS: frozenset[str] = frozenset(_SNAPSHOT["metrics"])
METRIC_DIRECTION: dict[str, str] = {
    name: spec["better"] for name, spec in _SNAPSHOT["metrics"].items()
}
TOOLS_BY_CATEGORY: dict[str, list[str]] = _SNAPSHOT["categories"]

# `proto_catalog.json` is the fuller per-tool schema the snapshot above was
# distilled from. It is read only for the one thing the distilled snapshot
# doesn't carry: which metrics a tool's own schema flags `primary` -- "the
# number you actually look at" rather than a secondary readout bundled
# alongside it. Read-only; never modified, per the same offline-snapshot
# contract as _SNAPSHOT_PATH above.
_CATALOG_PATH = Path(__file__).resolve().parents[3] / "registry" / "proto_catalog.json"

with _CATALOG_PATH.open() as _fh:
    _CATALOG = json.load(_fh)

_PRIMARY_METRICS: frozenset[str] = frozenset(
    measure["metric"]
    for tool in _CATALOG["tools"]
    for measure in tool.get("measures", [])
    if measure.get("primary")
)

# A metric counts as "widely shared" when several unrelated tools emit it --
# these are the confidence signals a design is likely to lean on regardless
# of which specific predictor ends up in the cascade.
_WIDELY_SHARED_MIN_TOOLS = 5
_WIDELY_SHARED_METRICS: frozenset[str] = frozenset(
    name for name, spec in _SNAPSHOT["metrics"].items()
    if len(spec["tools"]) >= _WIDELY_SHARED_MIN_TOOLS
)

# A metric is an interface metric when every tool emitting it is a complex
# scorer. Derived rather than listed, so it cannot drift independently.
#
# "iptm" is checked as a substring, not a prefix: `protein_iptm`, `ligand_iptm`
# and `pair_chains_iptm` (boltz2-prediction) are all interface-predicted-TM
# variants that happen to put a qualifier in front. `chains_` (plural) and
# `i_` catch boltz2's per-chain-pair `chains_ptm` and germinal-design's
# `i_ptm` / `i_pae` -- both tools' own naming for "this value is about the
# interface, not a single chain" (contrast `chain_ptm`, singular, which is a
# per-chain fold-confidence value and deliberately NOT matched here).
INTERFACE_METRICS: frozenset[str] = frozenset(
    name for name in _SNAPSHOT["metrics"]
    if "iptm" in name
    or name.startswith(("ipsae", "pdockq", "chains_", "i_"))
    or "interface" in name
    or "iplddt" in name
)


# --------------------------------------------------------------------------
# cost tiers
# --------------------------------------------------------------------------
# Ordering the cascade cheap-first is the single highest-leverage decision in
# the design loop: the expensive tools should only ever see candidates that
# already survived the cheap ones. `validate.py` enforces non-decreasing cost.
#
# Cost is a curated engineering judgement that the registry cannot supply, so
# these stay hand-maintained -- but keyed by MODEL FAMILY (the part before the
# first '-') so that real `<model>-<action>` keys resolve.

CHEAP_FAMILIES = {
    "ablang", "blast", "codonfm", "dssp", "esm2", "esm3", "esmc", "esm_if1",
    "esmfold", "esmfold2", "evo1", "evo2", "foldmason", "foldseek", "mafft",
    "mmseqs2", "progen2", "progen3", "proteinmpnn", "tmalign", "usalign",
    "uniprot", "pdb", "ncbi", "ensembl", "alphafold",
}
MODERATE_FAMILIES = {
    "boltz2", "chai1", "protenix", "ligandmpnn", "fampnn", "metal3d",
    "pdockq2", "ipsae", "vina", "pyrosetta", "opendde",
}
EXPENSIVE_FAMILIES = {
    "alphafold2", "alphafold3", "rf3", "bioemu", "bindcraft", "freebindcraft",
    "germinal",
}

COST_TIERS = ("cheap", "moderate", "expensive")
_COST_RANK = {tier: i for i, tier in enumerate(COST_TIERS)}


def _family(tool_key: str) -> str:
    return tool_key.split("-", 1)[0]


def cost_tier(tool_key: str) -> str:
    """Best-known cost tier for a tool key; unknown families are costly."""
    family = _family(tool_key)
    if family in EXPENSIVE_FAMILIES:
        return "expensive"
    if family in MODERATE_FAMILIES:
        return "moderate"
    if family in CHEAP_FAMILIES:
        return "cheap"
    return "expensive"


def cost_rank(tier: str) -> int:
    return _COST_RANK.get(tier, len(COST_TIERS))


def gate_cost_tier(tool_keys: list[str]) -> str:
    """A gate costs what its most expensive tool costs."""
    if not tool_keys:
        return "cheap"
    return max((cost_tier(k) for k in tool_keys), key=cost_rank)


def unknown_tools(keys: list[str]) -> list[str]:
    return sorted({k for k in keys if k not in PROTO_TOOL_KEYS})


def catalogue_digest() -> str:
    """Compact tool listing for a prompt. Grouped so selection is informed."""
    lines = []
    for category, keys in sorted(TOOLS_BY_CATEGORY.items()):
        lines.append(f"{category.replace('_', ' ')}: {', '.join(sorted(keys))}")
    return "\n".join(lines)


def metric_digest() -> str:
    """Compact, direction-grouped metric listing for a prompt.

    Deliberately NOT the full 170-metric snapshot -- dumping all of it would
    swamp the prompt and get skimmed rather than read. This renders the
    subset a model designing a cascade is actually likely to need: metrics
    the registry flags `primary` for at least one tool, plus metrics several
    different tools emit (the shared confidence vocabulary -- avg_plddt,
    iptm, and the like). Grouped by `better=` direction so a gate cannot
    threshold one backwards without the prompt itself having said which way
    is which.
    """
    selected = (_PRIMARY_METRICS | _WIDELY_SHARED_METRICS) & PROTO_METRICS
    by_direction: dict[str, list[str]] = {}
    for name in selected:
        by_direction.setdefault(METRIC_DIRECTION.get(name, "context-dependent"), []).append(name)

    lines = []
    for direction in ("higher", "lower", "context-dependent"):
        names = sorted(by_direction.get(direction, []))
        if names:
            lines.append(f"better={direction}: {', '.join(names)}")
    return "\n".join(lines)
